### ISSUE TITLE
Models not loading in the viewer

### ISSUE THREAD

**Issue by afshinjafari** [cyrillef/extract.autodesk.io#8] opened 2016-11-28 05:57 UTC
Hi,
I finally got the extractor working by changing some lines in the config file and extend the timeout for my larger models.
however trying to load models in the offline mode I receive this errors:

**viewer3D.min.js:1 THREE.DDSLoader.parse: Unsupported FourCC code 
viewer3D.min.js:1 THREE.DDSLoader.parse: Unsupported FourCC code  A
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost/0/0.pf**

I checked the contents of the '0' folder and 0.pf is not there for neither of the models converted.

I'm not confident the output file is containing all files?
any ideas?

Regards,
Afshin

**Comment by cyrillef** [comment] 2016-11-28 16:50
hum, not sure
at this stage does the model shows in the viewer before extraction?
if it does, I would be curious to know what file type you are using and if I can try on my side the model or similar one
make sure to pull the latest changes I posted as well

**Comment by afshinjafari** [comment] 2016-11-28 20:25
Yes, the model loads in the viewer, I can see it's downloading files in the background when pressing 'process' but not a .pf file.
I tried a .nwd file as well as .nwc
I downloaded yesterday morning, will try again to make sure it's latest.
happy to share the files, though not in public :)

**update**:
I just uploaded a sample model with the extracted files here:
https://www.dropbox.com/sh/may82rqkv3nyugh/AACUmGV_PvY_t567MvVpSaa0a?dl=0

**update 2**
I just made a test with the same model using extract.autodesk.io (https://extract.autodesk.io/explore/8318994-CV031-C_R1nwd)
the zip file (copied into the dropbox folder above [.online]) downloaded from the online version contains all pack files and materials.gz while the locally hosted extract does not contain these files in the zip file.
However the viewer still cannot load the model!

are you sure you have posted the same version here?

**Comment by afshinjafari** [comment] 2016-11-28 21:46
I just uploaded a sample model with the extracted files here:
https://www.dropbox.com/sh/may82rqkv3nyugh/AACUmGV_PvY_t567MvVpSaa0a?dl=0

**Comment by afshinjafari** [comment] 2016-11-28 22:18
I just made a test with the same model using extract.autodesk.io (https://extract.autodesk.io/explore/8318994-CV031-C_R1nwd)
the zip file downloaded from the online version contains all pack files and materials while the locally hosted extract does not contain these files in the zip file.

are you sure you have posted the same version here?

**Comment by AlanRitchie** [comment] 2016-11-29 11:02
I am using a .nwd model as well, and when I run the zip made from this version it doesn't display a model.  The browser console errors are:
`DOM7009: Unable to decode image at URL: 'http://localhost:8080/0/0.svf.png'.
File: 0.svf.png

THREE.DDSLoader.parse: Unsupported FourCC code  

THREE.DDSLoader.parse: Unsupported FourCC code  A`

The first is the png issue I posted as another thread.

Also there is no .pf model in the zip file, and the server reports a 404 error for GET /0/0.pf.

**Comment by afshinjafari** [comment] 2016-11-29 21:34
Hi Cyrille,
Seems it's not just me... any update on this? Any time frame will be appreciated as our project is heavily relying on this.
regards,
Afshin

**Comment by cyrillef** [comment] 2016-12-01 14:03
I replied on the ticket you submitted to us - I cannot reproduce the problem on my side. Any chance we could share screens to track the issue?

**Comment by cyrillef** [comment] 2016-12-01 14:12
actually someone raised another issue which might be related. Checkout out: https://github.com/cyrillef/extract.autodesk.io/issues/9

I'll document it right now

**Comment by AlanRitchie** [comment] 2016-12-01 18:02
Thanks Cyrille, I now get the .pf files in the zip.

Next issue was that the model didn't show in the local view, but I found views/view.ejs is missing "width:" for div#viewer

So I changed
`div#viewer { calc(100% - 190px); height: 700px; cursor: pointer; padding: 0px; margin-bottom: 20px; position: relative; overflow: hidden;`
to 
`div#viewer { width: calc(100% - 190px); height: 700px; cursor: pointer; padding: 0px; margin-bottom: 20px; position: relative; overflow: hidden;`
and I have a working model viewer.

**Comment by cyrillef** [comment] 2016-12-01 20:45
oops, my bad :(
Thx for the not and happy to hear it is working fine now
closing the tickets

**Closed as completed by cyrillef** 2016-12-01 20:45 UTC
